### ISSUE TITLE
Angle detection detail

### ISSUE THREAD

**Issue by trungpham2606** [ivan-alles/localizer#4]
Thank @ivan-alles for sharing a great work.
Iam quite curious about the method you used for detecting the orientation of the objects.
Can you explain it a bit or give me a reference to look at ?
Thank you in advance.

**Comment by ivan-alles** [comment]
You are welcome! The orientation is predicted in the form cos(angle), sin(angle). The ground truth is computed [here](https://github.com/ivan-alles/localizer/blob/52b49445bebf966ce7777d76f0fefdfd4a88ba86/localizer/dataset.py#L211). Then it is trained with the [MSE loss](https://github.com/ivan-alles/localizer/blob/52b49445bebf966ce7777d76f0fefdfd4a88ba86/localizer/train.py#L556).

**Comment by trungpham2606** [comment]
Thanks @ivan-alles for your explanation.
If I understand correctly, the loss for angle is the difference between sin(angle predict), cos(angle predict) and sin(angle gt), cos(angle gt) ?
Can you tell me the range of the angle ? is it [0-360] ?

**Comment by ivan-alles** [comment]
Yes, this is the squared difference. The angle itself is in the range -180/180 or -pi/pi, both conventions are used in the code.

**Comment by trungpham2606** [comment]
@ivan-alles 
In the dataset file I saw the line:
![image](https://user-images.githubusercontent.com/35657426/139395916-1f59f55d-611e-4d26-bbda-91e67c15a952.png)
I dont understand the usage of random_angle in here. Can you explain a bit about it ?

**Comment by ivan-alles** [comment]
I use data augmentation for training. It rotates the picture by a random angle. So, we need to correct the ground truth (obj.angle) by this random angle.

**Comment by trungpham2606** [comment]
Got it @ivan-alles 
Do you think I should use your angle definition ? because now my angle annotation is related to y-axis and in a range [0, 360].
![image](https://user-images.githubusercontent.com/35657426/139398025-451a35ba-a8f0-4e33-916f-7f72d4bd3719.png)

**Comment by ivan-alles** [comment]
It's up to you, they are all equal. I like mine, because it is compatible with opencv and image coordinate system.
