### ISSUE TITLE
Can't use the model for inference

### ISSUE THREAD

**Issue by Ahmed-Sadek** [ivan-alles/localizer#6]
I got this error when I have tried this command "!python localizer/predict_for_images.py models/tools/config.json datasets/tools".  Could you please help me?
<img width="639" alt="Screen Shot 2021-12-17 at 9 55 34 AM" src="https://user-images.githubusercontent.com/38966531/146511392-71ac5876-2ad1-4dd1-bdb4-9aae01201420.png">

**Comment by ivan-alles** [comment]
The first line in the log suggests that you are using TF 2.5 or higher, I tested on 2.4 (see Pipfile.lock). Might be a breaking change in TF.
