### ISSUE TITLE
Can I use localizer with YOLO?

### ISSUE THREAD

**Issue by khandriod** [ivan-alles/localizer#7]
Thanks for your good work. I want to know if it is possible to use a localizer with YOLO? 
I want to detect an object (bounding boxes) and its orientation at the same time.

**Comment by ivan-alles** [comment]
You can run Localizer and YOLO separately on images. You need to train Localizer on your objects first. 

If your objects are fixed-sized (e.g. some industrial components), it is also possible to compute bounded boxes from positions and orientations predicted by Localizer. You don't need YOLO in this case.
