### ISSUE TITLE
Deprecated dependencies

### ISSUE THREAD

**Issue by Gaoyuan-Liu** [ivan-alles/localizer#8]
Hey @ivan-alles ,
Nice work! I'm trying to use the package on a ubuntu 20.04, with python 3.9. However there are some dependencies that are deprecated, e.g., the robogym. 

I also see that you just use limited functions from robogym, so do you think it's possible to remove the dependency on robogym? 

Thanks in advance.

**Comment by ivan-alles** [comment]
Of course, it is possible in principle. You can do it in your fork.
